//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop.Controllers.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder
    {
        public int Id { get; set; }
        public string Orders { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
