//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.Controllers.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStudent
    {
        public int Id { get; set; }
        public int Sid { get; set; }
        public int CourseId { get; set; }
        public string Status { get; set; }
        public string Grade { get; set; }
        public Nullable<double> Marks { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
